### ISSUE TITLE
Milestone list for `v0.1.0`

### ISSUE THREAD

**Issue by trappitsch** [trappitsch/qtantic#10]
The following list are a minimum for `v0.1.0`.

- [x] Simple dialog
- [x] Tabbed dialog
- [ ] Multi tabbed dialog (one tab general, more tabs automatically generated and user filled)
- [ ] Tabbed dialog: Restore defaults for current vs. restore defaults for all
- [ ] Save path for a json config file
- [ ] Load from a json config file
- [ ] Save as option where a path is passed
